export interface Brand {
  id: string;
  name: string;
  categories: string[];
  offer: string;
  color: string;
  image?: string;
  bgColor?: string;
}

export const BRAND_CATEGORIES = [
  'All',
  'Quick Commerce',
  'New Brands',
  'Instore Brands',
  'Jewellery',
  'Food',
  'Grocery',
  'E-Commerce',
  'Hot Deals',
  'Travel & Transport',
  'Hotels',
  'Fashion',
  'Beauty',
  'Gaming',
  'Watches',
  'Entertainment',
  'Luxury',
  'Electronics',
  'Furnishing',
  'Fitness',
  'Accessories',
  'Kids',
  'Pharmacy',
  'Footwear',
  'OTT',
  'Hand Bags',
];

const GRADIENTS = [
  'from-emerald-500 to-teal-600',
  'from-pink-500 to-rose-600',
  'from-blue-500 to-indigo-600',
  'from-amber-500 to-orange-600',
  'from-purple-500 to-violet-600',
  'from-cyan-500 to-blue-600',
  'from-red-500 to-rose-600',
  'from-green-500 to-emerald-600',
  'from-yellow-400 to-amber-600',
  'from-indigo-500 to-purple-600',
  'from-fuchsia-500 to-pink-600',
  'from-slate-500 to-slate-700',
];

interface RawBrand {
  name: string;
  categories: string[];
  offer: string;
  image?: string;
  bgColor?: string;
}

const RAW_BRANDS: RawBrand[] = [
  { name: 'Blinkit', categories: ['Quick Commerce', 'New Brands'], offer: 'Up to 8% Cashback' },
  { name: 'Zepto', categories: ['Quick Commerce', 'New Brands'], offer: 'Flat 10% Off' },
  { name: 'Swiggy Instamart', categories: ['Quick Commerce', 'Food'], offer: 'Up to 6% Cashback' },
  { name: 'BigBasket', categories: ['Quick Commerce', 'Grocery'], offer: '5% Cashback' },
  { name: 'JioMart', categories: ['Grocery', 'E-Commerce'], offer: 'Up to 7% Off' },
  { name: "Nature's Basket", categories: ['Grocery'], offer: '5% Cashback' },
  { name: 'DMart Ready', categories: ['Grocery', 'Instore Brands'], offer: '3% Cashback' },
  { name: 'Reliance Trends', categories: ['Instore Brands', 'Fashion'], offer: 'Up to 12% Off' },
  { name: 'Lifestyle', categories: ['Instore Brands', 'Fashion'], offer: 'Up to 10% Off' },
  { name: 'Croma', categories: ['Instore Brands', 'Electronics'], offer: 'Up to 8% Cashback' },
  { name: 'Decathlon', categories: ['Instore Brands', 'Fitness'], offer: '5% Cashback' },
  { name: 'Tanishq', categories: ['Jewellery'], offer: 'Up to 4% Cashback' },
  { name: 'CaratLane', categories: ['Jewellery', 'New Brands'], offer: 'Up to 6% Off' },
  { name: 'Malabar Gold & Diamonds', categories: ['Jewellery'], offer: '3% Cashback' },
  { name: 'Kalyan Jewellers', categories: ['Jewellery'], offer: 'Flat 5% Off' },
  { name: 'Zomato', categories: ['Food', 'Hot Deals'], offer: 'Up to 15% Off' },
  { name: 'Swiggy', categories: ['Food', 'Hot Deals'], offer: 'Up to 12% Off' },
  { name: "Domino's Pizza", categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/dominos.png', bgColor: '#0b85ba' },
  { name: "McDonald's India", categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/mcdonalds.png', bgColor: '#c21616' },
  { name: 'Amazon', categories: ['E-Commerce', 'Hot Deals'], offer: 'Up to 10% Cashback' },
  { name: 'Flipkart', categories: ['E-Commerce', 'Hot Deals'], offer: 'Up to 10% Cashback' },
  { name: 'Myntra', categories: ['E-Commerce', 'Fashion'], offer: 'Up to 12% Off' },
  { name: 'Ajio', categories: ['E-Commerce', 'Fashion'], offer: 'Flat 15% Off' },
  { name: 'MakeMyTrip', categories: ['Travel & Transport', 'Hotels'], offer: 'Up to 12% Off' },
  { name: 'Uber', categories: ['Travel & Transport'], offer: 'Flat 10% Cashback' },
  { name: 'Ola', categories: ['Travel & Transport'], offer: 'Up to 8% Cashback' },
  { name: 'IRCTC', categories: ['Travel & Transport'], offer: 'Zero Convenience Fee' },
  { name: 'Cleartrip', categories: ['Travel & Transport', 'Hotels'], offer: 'Up to 10% Off' },
  { name: 'OYO Rooms', categories: ['Hotels', 'Travel & Transport'], offer: 'Flat 15% Off' },
  { name: 'Taj Hotels', categories: ['Hotels', 'Luxury', 'Food'], offer: 'Up to 8% Off', image: '/brand-logos/food/taj-dining.png', bgColor: '#2f2a25' },
  { name: 'Marriott Bonvoy', categories: ['Hotels', 'Luxury', 'Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/marriott-dining.png', bgColor: '#242420' },
  { name: 'ITC Hotels', categories: ['Hotels'], offer: '5% Cashback' },
  { name: 'H&M', categories: ['Fashion'], offer: 'Up to 10% Off' },
  { name: 'Zara', categories: ['Fashion'], offer: 'Up to 8% Off' },
  { name: 'Bewakoof', categories: ['Fashion', 'New Brands'], offer: 'Flat 20% Off' },
  { name: 'Nykaa', categories: ['Beauty', 'New Brands'], offer: 'Up to 12% Cashback' },
  { name: 'Sephora', categories: ['Beauty'], offer: 'Up to 10% Off' },
  { name: 'The Body Shop', categories: ['Beauty'], offer: 'Flat 15% Off' },
  { name: 'Mamaearth', categories: ['Beauty'], offer: 'Up to 10% Cashback' },
  { name: 'Steam', categories: ['Gaming'], offer: '5% Cashback' },
  { name: 'PlayStation Store', categories: ['Gaming', 'Entertainment'], offer: 'Up to 8% Off' },
  { name: 'Xbox', categories: ['Gaming', 'Entertainment'], offer: 'Up to 8% Off' },
  { name: 'Games24x7', categories: ['Gaming', 'New Brands'], offer: 'Welcome Bonus' },
  { name: 'Titan', categories: ['Watches', 'Accessories'], offer: 'Up to 6% Cashback' },
  { name: 'Fossil', categories: ['Watches', 'Accessories', 'Hand Bags'], offer: 'Up to 10% Off' },
  { name: 'Fastrack', categories: ['Watches', 'Accessories'], offer: 'Flat 15% Off' },
  { name: 'Casio', categories: ['Watches'], offer: '5% Cashback' },
  { name: 'BookMyShow', categories: ['Entertainment', 'Hot Deals'], offer: 'Up to 20% Off' },
  { name: 'PVR INOX', categories: ['Entertainment'], offer: 'Flat 10% Off' },
  { name: 'Cinepolis', categories: ['Entertainment'], offer: 'Buy 1 Get 1' },
  { name: 'Tata CLiQ Luxury', categories: ['Luxury', 'E-Commerce'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/tata-cliq-luxury.png', bgColor: '#efb5c0' },
  { name: 'Louis Philippe', categories: ['Fashion'], offer: 'Up to 8% Off' },
  { name: 'Reliance Digital', categories: ['Electronics', 'Instore Brands'], offer: 'Up to 8% Cashback' },
  { name: 'Vijay Sales', categories: ['Electronics', 'Instore Brands'], offer: 'Up to 7% Off' },
  { name: 'Apple Store', categories: ['Electronics'], offer: 'No Cost EMI' },
  { name: 'Pepperfry', categories: ['Furnishing'], offer: 'Up to 12% Off' },
  { name: 'Urban Ladder', categories: ['Furnishing'], offer: 'Up to 10% Off' },
  { name: 'IKEA', categories: ['Furnishing', 'Instore Brands'], offer: '5% Cashback' },
  { name: 'Cult.fit', categories: ['Fitness', 'New Brands'], offer: 'Up to 15% Off Membership' },
  { name: 'HealthifyMe', categories: ['Fitness'], offer: 'Flat 20% Off' },
  { name: 'Nike', categories: ['Footwear', 'Fitness'], offer: 'Up to 10% Off' },
  { name: 'Adidas', categories: ['Footwear', 'Fitness'], offer: 'Up to 10% Off' },
  { name: 'Bata', categories: ['Footwear'], offer: 'Flat 15% Off' },
  { name: 'Metro Shoes', categories: ['Footwear', 'Hand Bags'], offer: 'Up to 12% Off' },
  { name: 'FirstCry', categories: ['Kids'], offer: 'Up to 10% Cashback' },
  { name: 'Hamleys', categories: ['Kids', 'Hot Deals', 'Luxury'], offer: 'Flat 20% Off', image: '/brand-logos/luxury/hamleys.png', bgColor: '#fb0d47' },
  { name: 'Mothercare', categories: ['Kids', 'Luxury'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/mothercare.png', bgColor: '#31487b' },
  { name: 'PharmEasy', categories: ['Pharmacy'], offer: 'Up to 20% Off Medicines' },
  { name: 'Tata 1mg', categories: ['Pharmacy', 'New Brands'], offer: 'Up to 15% Off' },
  { name: 'Apollo Pharmacy', categories: ['Pharmacy'], offer: '5% Cashback' },
  { name: 'Netflix', categories: ['OTT', 'Entertainment'], offer: 'Gift Card Cashback' },
  { name: 'Amazon Prime Video', categories: ['OTT'], offer: 'Bundled Offers' },
  { name: 'Disney+ Hotstar', categories: ['OTT', 'Entertainment'], offer: 'Up to 10% Off Subscription' },
  { name: 'SonyLIV', categories: ['OTT'], offer: 'Up to 10% Off Subscription' },
  { name: 'Caprese', categories: ['Hand Bags', 'Accessories'], offer: 'Up to 15% Off' },
  { name: 'Hidesign', categories: ['Hand Bags'], offer: 'Up to 10% Off' },
  { name: 'Baggit', categories: ['Hand Bags', 'Accessories'], offer: 'Flat 20% Off' },
  { name: 'Lavie', categories: ['Hand Bags', 'Fashion'], offer: 'Up to 15% Off' },
  { name: 'American Tourister', categories: ['Accessories', 'Hand Bags'], offer: 'Up to 12% Off' },
  { name: 'Wildcraft', categories: ['Accessories'], offer: 'Up to 10% Off' },

  // Luxury category brand partners
  { name: 'Ajio Luxe', categories: ['Luxury', 'E-Commerce', 'Fashion'], offer: 'Up to 15% Off', image: '/brand-logos/luxury/ajio-luxe.png', bgColor: '#583d2d' },
  { name: 'Armani Exchange', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/armani-exchange.png', bgColor: '#e4d3b3' },
  { name: 'Bally', categories: ['Luxury', 'Footwear', 'Hand Bags'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/bally.png', bgColor: '#e2d3b3' },
  { name: 'Bottega Veneta', categories: ['Luxury', 'Hand Bags', 'Fashion'], offer: 'Up to 6% Off', image: '/brand-logos/luxury/bottega-veneta.png', bgColor: '#dfd1b4' },
  { name: 'Brooks Brothers', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/brooks-brothers.png', bgColor: '#e2d3b5' },
  { name: 'Canali', categories: ['Luxury', 'Fashion'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/canali.png', bgColor: '#e1d1b2' },
  { name: 'Coach', categories: ['Luxury', 'Hand Bags', 'Accessories'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/coach.png', bgColor: '#e3d4b5' },
  { name: 'Diesel', categories: ['Luxury', 'Fashion'], offer: 'Flat 15% Off', image: '/brand-logos/luxury/diesel.png', bgColor: '#d61d24' },
  { name: 'Dune London', categories: ['Luxury', 'Footwear'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/dune-london.png', bgColor: '#e2d2b3' },
  { name: 'Emporio Armani', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/emporio-armani.png', bgColor: '#e3d4b5' },
  { name: 'Salvatore Ferragamo', categories: ['Luxury', 'Footwear', 'Hand Bags'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/ferragamo.png', bgColor: '#e3d4b5' },
  { name: 'G-Star RAW', categories: ['Luxury', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/g-star-raw.png', bgColor: '#e4d5b6' },
  { name: 'Gas', categories: ['Luxury', 'Fashion'], offer: 'Flat 20% Off', image: '/brand-logos/luxury/gas.png', bgColor: '#e2d2b3' },
  { name: 'Giorgio Armani', categories: ['Luxury', 'Fashion'], offer: 'Up to 6% Off', image: '/brand-logos/luxury/giorgio-armani.png', bgColor: '#e4d4b5' },
  { name: 'Helios', categories: ['Luxury', 'Watches'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/helios.png', bgColor: '#010101' },
  { name: 'Hugo Boss', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/hugo-boss.png', bgColor: '#e3d4b5' },
  { name: 'Hunkemoller', categories: ['Luxury', 'Fashion'], offer: 'Flat 15% Off', image: '/brand-logos/luxury/hunkemoller.png', bgColor: '#e4d5b6' },
  { name: 'Abraham & Thakore', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/abraham-thakore.png', bgColor: '#030303' },
  { name: 'Adidas Kids', categories: ['Luxury', 'Kids', 'Footwear'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/adidas-kids.png', bgColor: '#0e1d40' },
  { name: 'AK-OK Anamika Khanna', categories: ['Luxury', 'Fashion'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/anamika-khanna.png', bgColor: '#000000' },
  { name: 'Charles Tyrwhitt', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/charles-tyrwhitt.png', bgColor: '#01214d' },
  { name: 'EA7 Emporio Armani', categories: ['Luxury', 'Fitness', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/ea7-emporio-armani.png', bgColor: '#020202' },
  { name: 'Kimirica', categories: ['Luxury', 'Beauty'], offer: 'Flat 20% Off', image: '/brand-logos/luxury/kimirica.png', bgColor: '#f8d4d8' },
  { name: 'Maje', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/maje.png', bgColor: '#0a0a09' },
  { name: 'Muji', categories: ['Luxury', 'Furnishing', 'Fashion'], offer: 'Up to 6% Cashback', image: '/brand-logos/luxury/muji.png', bgColor: '#810016' },
  { name: 'Pottery Barn', categories: ['Luxury', 'Furnishing'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/pottery-barn.png', bgColor: '#f4eee4' },
  { name: 'Pret A Manger', categories: ['Luxury', 'Food'], offer: 'Flat 15% Off', image: '/brand-logos/luxury/pret.png', bgColor: '#f8dde2' },
  { name: 'Ritu Kumar', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/ritu-kumar.png', bgColor: '#ffdec0' },
  { name: 'Rowan', categories: ['Luxury', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/rowan.png', bgColor: '#040404' },
  { name: 'Sunglass Hut', categories: ['Luxury', 'Accessories'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/sunglass-hut.png', bgColor: '#241f20' },
  { name: 'Tod\'s', categories: ['Luxury', 'Footwear', 'Hand Bags'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/tods.png', bgColor: '#1b1510' },
  { name: 'Tory Burch', categories: ['Luxury', 'Hand Bags', 'Fashion'], offer: 'Up to 6% Off', image: '/brand-logos/luxury/tory-burch.png', bgColor: '#7d8b49' },
  { name: 'Versace', categories: ['Luxury', 'Beauty', 'Fashion'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/versace.png', bgColor: '#7bbfbc' },
  { name: 'West Elm', categories: ['Luxury', 'Furnishing'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/west-elm.png', bgColor: '#e6e3df' },
  { name: 'ITC Hotel Spa Services', categories: ['Luxury', 'Hotels'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/itc-hotel.png', bgColor: '#f1ede4' },
  { name: 'Jimmy Choo', categories: ['Luxury', 'Footwear', 'Hand Bags'], offer: 'Up to 6% Off', image: '/brand-logos/luxury/jimmy-choo.png', bgColor: '#e0d1b2' },
  { name: 'Kate Spade', categories: ['Luxury', 'Hand Bags', 'Accessories'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/kate-spade.png', bgColor: '#dbcbac' },
  { name: 'Michael Kors', categories: ['Luxury', 'Hand Bags', 'Watches'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/michael-kors.png', bgColor: '#e2d2b3' },
  { name: 'Myntra Luxe', categories: ['Luxury', 'E-Commerce', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/myntra-luxe.png', bgColor: '#0a0a09' },
  { name: 'Nykaa Luxe', categories: ['Luxury', 'Beauty', 'E-Commerce'], offer: 'Up to 10% Cashback', image: '/brand-logos/luxury/nykaa-luxe.png', bgColor: '#f25e7d' },
  { name: 'Paul & Shark', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/paul-and-shark.png', bgColor: '#e4d3b3' },
  { name: 'Paul Smith', categories: ['Luxury', 'Fashion'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/paul-smith.png', bgColor: '#e3d4b5' },
  { name: 'Replay', categories: ['Luxury', 'Fashion'], offer: 'Flat 15% Off', image: '/brand-logos/luxury/replay.png', bgColor: '#e2d2b2' },
  { name: 'Satya Paul', categories: ['Luxury', 'Fashion'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/satya-paul.png', bgColor: '#dcccad' },
  { name: 'Scotch & Soda', categories: ['Luxury', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/scotch-and-soda.png', bgColor: '#e4d4b4' },
  { name: 'Fabelle', categories: ['Luxury', 'Food'], offer: 'Flat 20% Off', image: '/brand-logos/luxury/fabelle.png', bgColor: '#251215' },
  { name: 'Steve Madden', categories: ['Luxury', 'Footwear'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/steve-madden.png', bgColor: '#e4d3b3' },
  { name: 'Superdry', categories: ['Luxury', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/superdry.png', bgColor: '#e3d4b4' },
  { name: 'Tumi', categories: ['Luxury', 'Accessories', 'Hand Bags'], offer: 'Up to 8% Off', image: '/brand-logos/luxury/tumi.png', bgColor: '#e4d4b6' },
  { name: 'Villeroy & Boch', categories: ['Luxury', 'Furnishing'], offer: 'Up to 10% Off', image: '/brand-logos/luxury/villeroy-and-boch.png', bgColor: '#e4d5b6' },
  { name: 'White Crow', categories: ['Luxury', 'Fashion'], offer: 'Up to 12% Off', image: '/brand-logos/luxury/white-crow.png', bgColor: '#e3d4b5' },
  // Food category brand partners
  { name: 'Muro', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/muro.png', bgColor: '#eee6da' },
  { name: 'Subway', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/subway.png', bgColor: '#008a39' },
  { name: 'Wow! China', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/wow-china.png', bgColor: '#ec2127' },
  { name: 'Wow! Chicken', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/wow-chicken.png', bgColor: '#f4782a' },
  { name: 'Swiggy One', categories: ['Food', 'Hot Deals'], offer: 'Membership Benefits', image: '/brand-logos/food/swiggy-one.png', bgColor: '#f3e8dc' },
  { name: 'Bakingo', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/bakingo.png', bgColor: '#201717' },
  { name: 'Blue Tokai Coffee Roasters', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/blue-tokai.png', bgColor: '#4bcade' },
  { name: 'District by Zomato', categories: ['Food', 'Entertainment'], offer: 'Up to 20% Off', image: '/brand-logos/food/district-by-zomato.png', bgColor: '#5931b4' },
  { name: 'EazyDiner', categories: ['Food'], offer: 'Up to 25% Off', image: '/brand-logos/food/eazydiner.png', bgColor: '#fa4515' },
  { name: 'Fricken', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/fricken.png', bgColor: '#110807' },
  { name: 'KFC', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/kfc.png', bgColor: '#f7002f' },
  { name: 'Lunchbox', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/lunchbox.png', bgColor: '#480074' },
  { name: 'Sweet Truth', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/sweet-truth.png', bgColor: '#422f30' },
  { name: 'The Good Bowl', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/the-good-bowl.png', bgColor: '#230f03' },
  { name: 'Toscano', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/toscano.png', bgColor: '#d1d7bf' },
  { name: 'Vaango!', categories: ['Food'], offer: 'Flat 10% Off', image: '/brand-logos/food/vaango.png', bgColor: '#f4cf07' },
  { name: "Wendy's", categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/wendys.png', bgColor: '#fd0024' },
  { name: 'Wow! Momo', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/wow-momo.png', bgColor: '#ffea01' },
  { name: 'Dabba & Co', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/dabba-and-co.png', bgColor: '#fbf8b8' },
  { name: 'Lite Bite Foods', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/lite-bite-foods.png', bgColor: '#e6e1da' },
  { name: 'Honest Bowl', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/honest-bowl.png', bgColor: '#ffd5c6' },
  { name: 'Street Foods by Punjab Grill', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/street-foods-punjab-grill.png', bgColor: '#212224' },
  { name: 'The Biryani Life', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/the-biryani-life.png', bgColor: '#fff2c9' },
  { name: 'Thalaiva Biryani', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/thalaiva-biryani.png', bgColor: '#ffcaca' },
  { name: 'Tim Hortons', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/tim-hortons.png', bgColor: '#cd0224' },
  { name: 'YOÜ MEE', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/youmee.png', bgColor: '#d0bca4' },
  { name: 'Absolute Barbecues', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/absolute-barbecues.png', bgColor: '#a1292b' },
  { name: 'Asia Seven', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/asia-seven.png', bgColor: '#cf7d80' },
  { name: 'Barbeque Nation', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/barbeque-nation.png', bgColor: '#cc4e0b' },
  { name: 'Baskin Robbins', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/baskin-robbins.png', bgColor: '#da5991' },
  { name: 'The Beer Cafe', categories: ['Food', 'Hot Deals'], offer: 'Up to 20% Off', image: '/brand-logos/food/beer-cafe.png', bgColor: '#533a33' },
  { name: 'Behrouz Biryani', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/behrouz-biryani.png', bgColor: '#170b02' },
  { name: 'Bikanervala', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/bikanervala.png', bgColor: '#340705' },
  { name: 'Cafe Coffee Day', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/cafe-coffee-day.png', bgColor: '#b91119' },
  { name: 'Cafe Delhi Heights', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/cafe-delhi-heights.png', bgColor: '#6f1f36' },
  { name: 'Chicago Pizza', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/chicago-pizza.png', bgColor: '#1d0f04' },
  { name: 'Costa Coffee', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/costa-coffee.png', bgColor: '#842326' },
  { name: 'EatSure', categories: ['Food'], offer: 'Up to 20% Off', image: '/brand-logos/food/eatsure.png', bgColor: '#4e3ec7' },
  { name: 'Faasos', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/faasos.png', bgColor: '#4d1283' },
  { name: 'FreshMenu', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/freshmenu.png', bgColor: '#fad30b' },
  { name: 'Machaan', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/machaan.png', bgColor: '#441c09' },
  { name: 'Mainland China', categories: ['Food'], offer: 'Flat 15% Off', image: '/brand-logos/food/mainland-china.png', bgColor: '#f20001' },
  { name: 'Oh! Calcutta', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/oh-calcutta.png', bgColor: '#bdc0c2' },
  { name: 'Organic India', categories: ['Food', 'Grocery'], offer: 'Up to 10% Cashback', image: '/brand-logos/food/organic-india.png', bgColor: '#059a35' },
  { name: 'Oven Story', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/ovenstory.png', bgColor: '#e9001d' },
  { name: 'Pizza Hut', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/pizza-hut.png', bgColor: '#cf2f37' },
  { name: 'Polar Bear', categories: ['Food'], offer: 'Flat 20% Off', image: '/brand-logos/food/polar-bear.png', bgColor: '#5fa2b1' },
  { name: 'Punjab Grill', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/punjab-grill.png', bgColor: '#000000' },
  { name: 'Sigree', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/sigree.png', bgColor: '#190902' },
  { name: 'Starbucks', categories: ['Food'], offer: 'Flat 10% Off', image: '/brand-logos/food/starbucks.png', bgColor: '#b79975' },
  { name: 'Sweet Bengal', categories: ['Food'], offer: 'Up to 10% Off', image: '/brand-logos/food/sweet-bengal.png', bgColor: '#eac9a2' },
  { name: 'TGI Fridays', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/tgi-fridays.png', bgColor: '#1a0a09' },
  { name: 'Third Wave Coffee', categories: ['Food'], offer: 'Flat 10% Off', image: '/brand-logos/food/third-wave-coffee.png', bgColor: '#30404b' },
  { name: 'Zambar', categories: ['Food'], offer: 'Up to 15% Off', image: '/brand-logos/food/zambar.png', bgColor: '#fee3ac' },
];

export const brands: Brand[] = RAW_BRANDS.map((b, i) => ({
  id: String(i + 1),
  name: b.name,
  categories: b.categories,
  offer: b.offer,
  color: GRADIENTS[i % GRADIENTS.length],
  image: b.image,
  bgColor: b.bgColor,
}));
