import { Card } from './types';

export const featuredCards: Card[] = [
  {
    id: '1',
    name: 'Cashback Credit Card',
    bank: 'SBI Card',
    issuer: 'SBI Card',
    type: 'Credit Card',
    image: 'https://images.unsplash.com/photo-1589750670744-dc9633e0f9c7?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    benefits: ['5% Unlimited Cashback', '1% Offline Cashback'],
    annualFee: '₹999',
    joiningFee: '₹999',
    bestFor: 'Online Spends & Swiggy',
    category: 'Cashback',
    color: 'from-blue-600 to-blue-800',
    rewardsRate: '5%',
    projectedSavings: '₹12,000/yr',
    features: ['5% Unlimited Cashback', '1% Offline Cashback']
  },
  {
    id: '2',
    name: 'Magnus Burgundy',
    bank: 'Axis Bank',
    issuer: 'Axis Bank',
    type: 'Credit Card',
    image: 'https://images.unsplash.com/photo-1613243555988-441166d4d6fd?auto=format&fit=crop&q=80&w=800',
    rating: 4.9,
    benefits: ['Unlimited Lounge Access', '24/7 Concierge'],
    annualFee: '₹30,000',
    joiningFee: '₹30,000',
    bestFor: 'High Spenders & Flights',
    category: 'Luxury Travel',
    color: 'from-purple-900 to-indigo-950',
    rewardsRate: '12%',
    projectedSavings: '₹45,000/yr',
    features: ['Unlimited Lounge Access', '24/7 Concierge']
  },
  {
    id: '3',
    name: 'Swiggy HDFC Card',
    bank: 'HDFC Bank',
    issuer: 'HDFC Bank',
    type: 'Credit Card',
    image: 'https://images.unsplash.com/photo-1556742049-02e49f9d2a10?auto=format&fit=crop&q=80&w=800',
    rating: 4.7,
    benefits: ['10% Swiggy Cashback', '5% Online Shopping'],
    annualFee: '₹500',
    joiningFee: '₹500',
    bestFor: 'Foodies & Dineout',
    category: 'Food & Dining',
    color: 'from-orange-500 to-red-600',
    rewardsRate: '10%',
    projectedSavings: '₹8,400/yr',
    features: ['10% Swiggy Cashback', '5% Online Shopping']
  },
  {
    id: '4',
    name: 'Amazon Pay ICICI',
    bank: 'ICICI Bank',
    issuer: 'ICICI Bank',
    type: 'Credit Card',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&q=80&w=800',
    rating: 4.8,
    benefits: ['5% Amazon Cashback', '2% Partner Spends'],
    annualFee: 'Free',
    joiningFee: 'Free',
    bestFor: 'Amazon Prime Members',
    category: 'Shopping',
    color: 'from-slate-800 to-slate-950',
    rewardsRate: '5%',
    projectedSavings: '₹6,000/yr',
    features: ['5% Amazon Cashback', '2% Partner Spends']
  }
];
