services:
  - type: web
    name: yureka-api
    env: node
    buildCommand: npm install --include=dev && npm run build && python3 -m venv venv && ./venv/bin/pip install -r backend/requirements.txt && npm prune --production
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
