-- FINAL UPGRADE SCRIPT FOR CARDS TABLE
-- Run this exactly as written in your Supabase SQL Editor

ALTER TABLE cards
  ADD COLUMN IF NOT EXISTS author text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS reward_type text,
  ADD COLUMN IF NOT EXISTS welcome_benefits text,
  ADD COLUMN IF NOT EXISTS product_details jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS pros jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS cons jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS detailed_features text,
  ADD COLUMN IF NOT EXISTS cashback_details text,
  ADD COLUMN IF NOT EXISTS redemption_table jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS exclusions text,
  ADD COLUMN IF NOT EXISTS eligibility_criteria jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS comparison_cards text,
  ADD COLUMN IF NOT EXISTS latest_news jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS final_review_image text,
  ADD COLUMN IF NOT EXISTS final_verdict_text text,
  ADD COLUMN IF NOT EXISTS grid_benefits jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS grid_fees jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS verdict text,
  ADD COLUMN IF NOT EXISTS joining_fee numeric,
  ADD COLUMN IF NOT EXISTS annual_fee numeric,
  ADD COLUMN IF NOT EXISTS rewards_rate numeric,
  ADD COLUMN IF NOT EXISTS rating numeric,
  ADD COLUMN IF NOT EXISTS elite_rating numeric,
  ADD COLUMN IF NOT EXISTS intro_offer text,
  ADD COLUMN IF NOT EXISTS projected_savings text,
  ADD COLUMN IF NOT EXISTS apply_link text,
  ADD COLUMN IF NOT EXISTS benefit_items jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS best_for text;
