name: Instant Search Indexing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  index-now-bing:
    name: Ping Bing (IndexNow)
    runs-on: ubuntu-latest
    steps:
      - name: IndexNow Action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://yureka.money/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: 'www.bing.com'

  google-indexing:
    name: Ping Google
    runs-on: ubuntu-latest
    steps:
      - name: Google Indexing Action
        uses: robingenz/action-google-indexing@v1.0.2
        with:
          siteUrl: 'https://yureka.money'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
